BEGIN;
ALTER TABLE haspermission DROP CONSTRAINT haspermission_roleid_fkey;
ALTER TABLE haspermission ADD FOREIGN KEY(roleid) REFERENCES roles(id) ON UPDATE CASCADE ON DELETE CASCADE;

ALTER TABLE hasrole DROP CONSTRAINT hasrole_roleid_fkey;
ALTER TABLE hasrole ADD FOREIGN KEY(roleid) REFERENCES roles(id) ON UPDATE CASCADE ON DELETE CASCADE;
COMMIT;
