BEGIN;

CREATE TABLE activity_tracks (
	id SERIAL PRIMARY KEY,
	name VARCHAR NOT NULL,
	description TEXT,
	usercompanyid INT NOT NULL REFERENCES organisations(id) ON UPDATE CASCADE ON DELETE CASCADE,
	created TIMESTAMP NOT NULL DEFAULT now(),
	owner VARCHAR NOT NULL REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE,
	lastupdated TIMESTAMP NOT NULL DEFAULT now(),
	alteredby VARCHAR NOT NULL REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE activity_track_stages (
	id SERIAL PRIMARY KEY,
	track_id INT NOT NULL REFERENCES activity_tracks(id) ON UPDATE CASCADE ON DELETE CASCADE,
	name VARCHAR NOT NULL,
	description TEXT,
	type_id INT REFERENCES activitytype(id) ON UPDATE CASCADE ON DELETE CASCADE,
	x_days INT,
	assigned_to VARCHAR REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE
);

COMMIT;
