BEGIN;

ALTER TABLE tactile_accounts ADD COLUMN theme VARCHAR NOT NULL DEFAULT 'green';
ALTER TABLE organisations ADD COLUMN logo_id INT REFERENCES s3_files(id) ON DELETE SET NULL ON UPDATE CASCADE;

COMMIT;