BEGIN;
UPDATE countries SET name = 'Afghanistan' WHERE code = 'AF';
UPDATE countries SET name = 'Albania' WHERE code = 'AL';
UPDATE countries SET name = 'Algeria' WHERE code = 'DZ';
UPDATE countries SET name = 'American Samoa' WHERE code = 'AS';
UPDATE countries SET name = 'Andorra' WHERE code = 'AD';
UPDATE countries SET name = 'Angola' WHERE code = 'AO';
UPDATE countries SET name = 'Anguilla' WHERE code = 'AI';
UPDATE countries SET name = 'Antarctica' WHERE code = 'AQ';
UPDATE countries SET name = 'Antigua and Barbuda' WHERE code = 'AG';
UPDATE countries SET name = 'Argentina' WHERE code = 'AR';
UPDATE countries SET name = 'Armenia' WHERE code = 'AM';
UPDATE countries SET name = 'Aruba' WHERE code = 'AW';
UPDATE countries SET name = 'Australia' WHERE code = 'AU';
UPDATE countries SET name = 'Austria' WHERE code = 'AT';
UPDATE countries SET name = 'Azerbaijan' WHERE code = 'AZ';
UPDATE countries SET name = 'Bahamas' WHERE code = 'BS';
UPDATE countries SET name = 'Bahrain' WHERE code = 'BH';
UPDATE countries SET name = 'Bangladesh' WHERE code = 'BD';
UPDATE countries SET name = 'Barbados' WHERE code = 'BB';
UPDATE countries SET name = 'Belarus' WHERE code = 'BY';
UPDATE countries SET name = 'Belgium' WHERE code = 'BE';
UPDATE countries SET name = 'Belize' WHERE code = 'BZ';
UPDATE countries SET name = 'Benin' WHERE code = 'BJ';
UPDATE countries SET name = 'Bermuda' WHERE code = 'BM';
UPDATE countries SET name = 'Bhutan' WHERE code = 'BT';
UPDATE countries SET name = 'Bolivia' WHERE code = 'BO';
UPDATE countries SET name = 'Bosnia and Herzegovina' WHERE code = 'BA';
UPDATE countries SET name = 'Botswana' WHERE code = 'BW';
UPDATE countries SET name = 'Bouvet Island' WHERE code = 'BV';
UPDATE countries SET name = 'Brazil' WHERE code = 'BR';
UPDATE countries SET name = 'British Indian Ocean Territory' WHERE code = 'IO';
UPDATE countries SET name = 'Brunei Darussalam' WHERE code = 'BN';
UPDATE countries SET name = 'Bulgaria' WHERE code = 'BG';
UPDATE countries SET name = 'Burkina Faso' WHERE code = 'BF';
UPDATE countries SET name = 'Burundi' WHERE code = 'BI';
UPDATE countries SET name = 'Cambodia' WHERE code = 'KH';
UPDATE countries SET name = 'Cameroon' WHERE code = 'CM';
UPDATE countries SET name = 'Canada' WHERE code = 'CA';
UPDATE countries SET name = 'Cape Verde' WHERE code = 'CV';
UPDATE countries SET name = 'Cayman Islands' WHERE code = 'KY';
UPDATE countries SET name = 'Central African Republic' WHERE code = 'CF';
UPDATE countries SET name = 'Chad' WHERE code = 'TD';
UPDATE countries SET name = 'Chile' WHERE code = 'CL';
UPDATE countries SET name = 'China' WHERE code = 'CN';
UPDATE countries SET name = 'Christmas Island' WHERE code = 'CX';
UPDATE countries SET name = 'Cocos Keeling) Islands' WHERE code = 'CC';
UPDATE countries SET name = 'Colombia' WHERE code = 'CO';
UPDATE countries SET name = 'Comoros' WHERE code = 'KM';
UPDATE countries SET name = 'Congo' WHERE code = 'CG';
UPDATE countries SET name = 'Congo, Democratic Republic of the' WHERE code = 'CD';
UPDATE countries SET name = 'Cook Islands' WHERE code = 'CK';
UPDATE countries SET name = 'Costa Rica' WHERE code = 'CR';
UPDATE countries SET name = 'Cote d''Ivoire  Côte d''Ivoire' WHERE code = 'CI';
UPDATE countries SET name = 'Croatia' WHERE code = 'HR';
UPDATE countries SET name = 'Cuba' WHERE code = 'CU';
UPDATE countries SET name = 'Cyprus' WHERE code = 'CY';
UPDATE countries SET name = 'Czech Republic' WHERE code = 'CZ';
UPDATE countries SET name = 'Denmark' WHERE code = 'DK';
UPDATE countries SET name = 'Djibouti' WHERE code = 'DJ';
UPDATE countries SET name = 'Dominica' WHERE code = 'DM';
UPDATE countries SET name = 'Dominican Republic' WHERE code = 'DO';
UPDATE countries SET name = 'Ecuador' WHERE code = 'EC';
UPDATE countries SET name = 'Egypt' WHERE code = 'EG';
UPDATE countries SET name = 'El Salvador' WHERE code = 'SV';
UPDATE countries SET name = 'Equatorial Guinea' WHERE code = 'GQ';
UPDATE countries SET name = 'Eritrea' WHERE code = 'ER';
UPDATE countries SET name = 'Estonia' WHERE code = 'EE';
UPDATE countries SET name = 'Ethiopia' WHERE code = 'ET';
UPDATE countries SET name = 'Falkland Islands Malvinas)' WHERE code = 'FK';
UPDATE countries SET name = 'Faroe Islands' WHERE code = 'FO';
UPDATE countries SET name = 'Fiji' WHERE code = 'FJ';
UPDATE countries SET name = 'Finland' WHERE code = 'FI';
UPDATE countries SET name = 'France' WHERE code = 'FR';
UPDATE countries SET name = 'French Guiana' WHERE code = 'GF';
UPDATE countries SET name = 'French Polynesia' WHERE code = 'PF';
UPDATE countries SET name = 'French Southern Territories' WHERE code = 'TF';
UPDATE countries SET name = 'Gabon' WHERE code = 'GA';
UPDATE countries SET name = 'Gambia' WHERE code = 'GM';
UPDATE countries SET name = 'Georgia' WHERE code = 'GE';
UPDATE countries SET name = 'Germany' WHERE code = 'DE';
UPDATE countries SET name = 'Ghana' WHERE code = 'GH';
UPDATE countries SET name = 'Gibraltar' WHERE code = 'GI';
UPDATE countries SET name = 'Greece' WHERE code = 'GR';
UPDATE countries SET name = 'Greenland' WHERE code = 'GL';
UPDATE countries SET name = 'Grenada' WHERE code = 'GD';
UPDATE countries SET name = 'Guadeloupe' WHERE code = 'GP';
UPDATE countries SET name = 'Guam' WHERE code = 'GU';
UPDATE countries SET name = 'Guatemala' WHERE code = 'GT';
UPDATE countries SET name = 'Guinea' WHERE code = 'GN';
UPDATE countries SET name = 'Guinea-Bissau' WHERE code = 'GW';
UPDATE countries SET name = 'Guyana' WHERE code = 'GY';
UPDATE countries SET name = 'Haiti' WHERE code = 'HT';
UPDATE countries SET name = 'Heard Island and McDonald Islands' WHERE code = 'HM';
UPDATE countries SET name = 'Holy See Vatican City State)' WHERE code = 'VA';
UPDATE countries SET name = 'Honduras' WHERE code = 'HN';
UPDATE countries SET name = 'Hong Kong' WHERE code = 'HK';
UPDATE countries SET name = 'Hungary' WHERE code = 'HU';
UPDATE countries SET name = 'Iceland' WHERE code = 'IS';
UPDATE countries SET name = 'India' WHERE code = 'IN';
UPDATE countries SET name = 'Indonesia' WHERE code = 'ID';
UPDATE countries SET name = 'Iran, Islamic Republic of' WHERE code = 'IR';
UPDATE countries SET name = 'Iraq' WHERE code = 'IQ';
UPDATE countries SET name = 'Ireland' WHERE code = 'IE';
UPDATE countries SET name = 'Israel' WHERE code = 'IL';
UPDATE countries SET name = 'Italy' WHERE code = 'IT';
UPDATE countries SET name = 'Jamaica' WHERE code = 'JM';
UPDATE countries SET name = 'Japan' WHERE code = 'JP';
UPDATE countries SET name = 'Jordan' WHERE code = 'JO';
UPDATE countries SET name = 'Kazakhstan' WHERE code = 'KZ';
UPDATE countries SET name = 'Kenya' WHERE code = 'KE';
UPDATE countries SET name = 'Kiribati' WHERE code = 'KI';
UPDATE countries SET name = 'Korea, Democratic People''s Republic of' WHERE code = 'KP';
UPDATE countries SET name = 'Korea, Republic of' WHERE code = 'KR';
UPDATE countries SET name = 'Kuwait' WHERE code = 'KW';
UPDATE countries SET name = 'Kyrgyzstan' WHERE code = 'KG';
UPDATE countries SET name = 'Lao People''s Democratic Republic' WHERE code = 'LA';
UPDATE countries SET name = 'Latvia' WHERE code = 'LV';
UPDATE countries SET name = 'Lebanon' WHERE code = 'LB';
UPDATE countries SET name = 'Lesotho' WHERE code = 'LS';
UPDATE countries SET name = 'Liberia' WHERE code = 'LR';
UPDATE countries SET name = 'Libyan Arab Jamahiriya' WHERE code = 'LY';
UPDATE countries SET name = 'Liechtenstein' WHERE code = 'LI';
UPDATE countries SET name = 'Lithuania' WHERE code = 'LT';
UPDATE countries SET name = 'Luxembourg' WHERE code = 'LU';
UPDATE countries SET name = 'Macao' WHERE code = 'MO';
UPDATE countries SET name = 'Macedonia, the former Yugoslav Republic of' WHERE code = 'MK';
UPDATE countries SET name = 'Madagascar' WHERE code = 'MG';
UPDATE countries SET name = 'Malawi' WHERE code = 'MW';
UPDATE countries SET name = 'Malaysia' WHERE code = 'MY';
UPDATE countries SET name = 'Maldives' WHERE code = 'MV';
UPDATE countries SET name = 'Mali' WHERE code = 'ML';
UPDATE countries SET name = 'Malta' WHERE code = 'MT';
UPDATE countries SET name = 'Marshall Islands' WHERE code = 'MH';
UPDATE countries SET name = 'Martinique' WHERE code = 'MQ';
UPDATE countries SET name = 'Mauritania' WHERE code = 'MR';
UPDATE countries SET name = 'Mauritius' WHERE code = 'MU';
UPDATE countries SET name = 'Mayotte' WHERE code = 'YT';
UPDATE countries SET name = 'Mexico' WHERE code = 'MX';
UPDATE countries SET name = 'Micronesia, Federated States of' WHERE code = 'FM';
UPDATE countries SET name = 'Moldova, Republic of' WHERE code = 'MD';
UPDATE countries SET name = 'Monaco' WHERE code = 'MC';
UPDATE countries SET name = 'Mongolia' WHERE code = 'MN';
UPDATE countries SET name = 'Montserrat' WHERE code = 'MS';
UPDATE countries SET name = 'Morocco' WHERE code = 'MA';
UPDATE countries SET name = 'Mozambique' WHERE code = 'MZ';
UPDATE countries SET name = 'Myanmar' WHERE code = 'MM';
UPDATE countries SET name = 'Namibia' WHERE code = 'NA';
UPDATE countries SET name = 'Nauru' WHERE code = 'NR';
UPDATE countries SET name = 'Nepal' WHERE code = 'NP';
UPDATE countries SET name = 'Netherlands' WHERE code = 'NL';
UPDATE countries SET name = 'Netherlands Antilles' WHERE code = 'AN';
UPDATE countries SET name = 'New Caledonia' WHERE code = 'NC';
UPDATE countries SET name = 'New Zealand' WHERE code = 'NZ';
UPDATE countries SET name = 'Nicaragua' WHERE code = 'NI';
UPDATE countries SET name = 'Niger' WHERE code = 'NE';
UPDATE countries SET name = 'Nigeria' WHERE code = 'NG';
UPDATE countries SET name = 'Niue' WHERE code = 'NU';
UPDATE countries SET name = 'Norfolk Island' WHERE code = 'NF';
UPDATE countries SET name = 'Northern Mariana Islands' WHERE code = 'MP';
UPDATE countries SET name = 'Norway' WHERE code = 'NO';
UPDATE countries SET name = 'Oman' WHERE code = 'OM';
UPDATE countries SET name = 'Pakistan' WHERE code = 'PK';
UPDATE countries SET name = 'Palau' WHERE code = 'PW';
UPDATE countries SET name = 'Palestinian Territory, Occupied' WHERE code = 'PS';
UPDATE countries SET name = 'Panama' WHERE code = 'PA';
UPDATE countries SET name = 'Papua New Guinea' WHERE code = 'PG';
UPDATE countries SET name = 'Paraguay' WHERE code = 'PY';
UPDATE countries SET name = 'Peru' WHERE code = 'PE';
UPDATE countries SET name = 'Philippines' WHERE code = 'PH';
UPDATE countries SET name = 'Pitcairn' WHERE code = 'PN';
UPDATE countries SET name = 'Poland' WHERE code = 'PL';
UPDATE countries SET name = 'Portugal' WHERE code = 'PT';
UPDATE countries SET name = 'Puerto Rico' WHERE code = 'PR';
UPDATE countries SET name = 'Qatar' WHERE code = 'QA';
UPDATE countries SET name = 'Reunion  Réunion' WHERE code = 'RE';
UPDATE countries SET name = 'Romania' WHERE code = 'RO';
UPDATE countries SET name = 'Russian Federation' WHERE code = 'RU';
UPDATE countries SET name = 'Rwanda' WHERE code = 'RW';
UPDATE countries SET name = 'Saint Helena' WHERE code = 'SH';
UPDATE countries SET name = 'Saint Kitts and Nevis' WHERE code = 'KN';
UPDATE countries SET name = 'Saint Lucia' WHERE code = 'LC';
UPDATE countries SET name = 'Saint Pierre and Miquelon' WHERE code = 'PM';
UPDATE countries SET name = 'Saint Vincent and the Grenadines' WHERE code = 'VC';
UPDATE countries SET name = 'Samoa' WHERE code = 'WS';
UPDATE countries SET name = 'San Marino' WHERE code = 'SM';
UPDATE countries SET name = 'Sao Tome and Principe' WHERE code = 'ST';
UPDATE countries SET name = 'Saudi Arabia' WHERE code = 'SA';
UPDATE countries SET name = 'Senegal' WHERE code = 'SN';
UPDATE countries SET name = 'Seychelles' WHERE code = 'SC';
UPDATE countries SET name = 'Sierra Leone' WHERE code = 'SL';
UPDATE countries SET name = 'Singapore' WHERE code = 'SG';
UPDATE countries SET name = 'Slovakia' WHERE code = 'SK';
UPDATE countries SET name = 'Slovenia' WHERE code = 'SI';
UPDATE countries SET name = 'Solomon Islands' WHERE code = 'SB';
UPDATE countries SET name = 'Somalia' WHERE code = 'SO';
UPDATE countries SET name = 'South Africa' WHERE code = 'ZA';
UPDATE countries SET name = 'South Georgia and the South Sandwich Islands' WHERE code = 'GS';
UPDATE countries SET name = 'Spain' WHERE code = 'ES';
UPDATE countries SET name = 'Sri Lanka' WHERE code = 'LK';
UPDATE countries SET name = 'Sudan' WHERE code = 'SD';
UPDATE countries SET name = 'Suriname' WHERE code = 'SR';
UPDATE countries SET name = 'Svalbard and Jan Mayen' WHERE code = 'SJ';
UPDATE countries SET name = 'Swaziland' WHERE code = 'SZ';
UPDATE countries SET name = 'Sweden' WHERE code = 'SE';
UPDATE countries SET name = 'Switzerland' WHERE code = 'CH';
UPDATE countries SET name = 'Syrian Arab Republic' WHERE code = 'SY';
UPDATE countries SET name = 'Taiwan, Province of China' WHERE code = 'TW';
UPDATE countries SET name = 'Tajikistan' WHERE code = 'TJ';
UPDATE countries SET name = 'Tanzania, United Republic of' WHERE code = 'TZ';
UPDATE countries SET name = 'Thailand' WHERE code = 'TH';
UPDATE countries SET name = 'Timor-Leste' WHERE code = 'TL';
UPDATE countries SET name = 'Togo' WHERE code = 'TG';
UPDATE countries SET name = 'Tokelau' WHERE code = 'TK';
UPDATE countries SET name = 'Tonga' WHERE code = 'TO';
UPDATE countries SET name = 'Trinidad and Tobago' WHERE code = 'TT';
UPDATE countries SET name = 'Tunisia' WHERE code = 'TN';
UPDATE countries SET name = 'Turkey' WHERE code = 'TR';
UPDATE countries SET name = 'Turkmenistan' WHERE code = 'TM';
UPDATE countries SET name = 'Turks and Caicos Islands' WHERE code = 'TC';
UPDATE countries SET name = 'Tuvalu' WHERE code = 'TV';
UPDATE countries SET name = 'Uganda' WHERE code = 'UG';
UPDATE countries SET name = 'Ukraine' WHERE code = 'UA';
UPDATE countries SET name = 'United Arab Emirates' WHERE code = 'AE';
UPDATE countries SET name = 'United Kingdom' WHERE code = 'GB';
UPDATE countries SET name = 'United States' WHERE code = 'US';
UPDATE countries SET name = 'United States Minor Outlying Islands' WHERE code = 'UM';
UPDATE countries SET name = 'Uruguay' WHERE code = 'UY';
UPDATE countries SET name = 'Uzbekistan' WHERE code = 'UZ';
UPDATE countries SET name = 'Vanuatu' WHERE code = 'VU';
UPDATE countries SET name = 'Venezuela, Bolivarian Republic of' WHERE code = 'VE';
UPDATE countries SET name = 'Viet Nam' WHERE code = 'VN';
UPDATE countries SET name = 'Virgin Islands, British' WHERE code = 'VG';
UPDATE countries SET name = 'Virgin Islands, U.S.' WHERE code = 'VI';
UPDATE countries SET name = 'Wallis and Futuna' WHERE code = 'WF';
UPDATE countries SET name = 'Western Sahara' WHERE code = 'EH';
UPDATE countries SET name = 'Yemen' WHERE code = 'YE';
UPDATE countries SET name = 'Zambia' WHERE code = 'ZM';
UPDATE countries SET name = 'Zimbabwe' WHERE code = 'ZW';
DELETE FROM countries WHERE code = 'YU';

INSERT INTO countries (name, code) VALUES ('Aland Islands  Åland Islands','AX');
INSERT INTO countries (name, code) VALUES ('Guernsey','GG');
INSERT INTO countries (name, code) VALUES ('Isle of Man','IM');
INSERT INTO countries (name, code) VALUES ('Jersey','JE');
INSERT INTO countries (name, code) VALUES ('Montenegro','ME');
INSERT INTO countries (name, code) VALUES ('Saint Barthélemy','BL');
INSERT INTO countries (name, code) VALUES ('Saint Martin French part)','MF');
INSERT INTO countries (name, code) VALUES ('Serbia','RS');
COMMIT;