BEGIN;

CREATE TABLE motds(
id SERIAL PRIMARY KEY,
message_start TIMESTAMP NOT NULL DEFAULT now(),
message_end TIMESTAMP,
active BOOLEAN NOT NULL DEFAULT FALSE,
important BOOLEAN NOT NULL DEFAULT FALSE,
content TEXT NOT NULL
);

COMMIT;