BEGIN;

-- Get rid of a crapload of unused tables
DROP TABLE account_statuses CASCADE;
DROP TABLE actions CASCADE;
DROP TABLE calendar_event_attendees CASCADE;
DROP TABLE calendar_shares CASCADE;
DROP TABLE campaigns CASCADE;
DROP TABLE campaignstatus CASCADE;
DROP TABLE campaigntype CASCADE;
DROP TABLE cb_accounts CASCADE;
DROP TABLE cb_transactions CASCADE;
DROP TABLE contact_categories CASCADE;
DROP TABLE cumaster CASCADE;
DROP TABLE curate CASCADE;
DROP TABLE customer_type_discounts CASCADE;
DROP TABLE customer_types CASCADE;
DROP TABLE customers CASCADE;
DROP TABLE customers_in_types CASCADE;
DROP TABLE dynamic_section_criteria CASCADE;
DROP TABLE employees CASCADE;
DROP TABLE entity_attachments CASCADE;
DROP TABLE faq CASCADE;
DROP TABLE faq_qa CASCADE;
DROP TABLE faq_qa_section CASCADE;
DROP TABLE faq_section CASCADE;
DROP TABLE galleries CASCADE;
DROP TABLE gallery_pictures CASCADE;
DROP TABLE glanalysis CASCADE;
DROP TABLE glbalance CASCADE;
DROP TABLE glcentre CASCADE;
DROP TABLE glelement CASCADE;
DROP TABLE glmaster CASCADE;
DROP TABLE glopening CASCADE;
DROP TABLE glparams CASCADE;
DROP TABLE glperiods CASCADE;
DROP TABLE glstandard CASCADE;
DROP TABLE glsummary CASCADE;
DROP TABLE gltransaction CASCADE;
DROP TABLE holiday_entitlements CASCADE;
DROP TABLE holiday_extra_days CASCADE;
DROP TABLE holiday_requests CASCADE;
DROP TABLE hour_type_groups CASCADE;
DROP TABLE hour_types CASCADE;
DROP TABLE intranet_config CASCADE;
DROP TABLE intranet_layouts CASCADE;
DROP TABLE intranet_page_access CASCADE;
DROP TABLE intranet_page_files CASCADE;
DROP TABLE intranet_page_revisions CASCADE;
DROP TABLE intranet_page_types CASCADE;
DROP TABLE intranet_pages CASCADE;
DROP TABLE intranet_postings CASCADE;
DROP TABLE intranet_section_access CASCADE;
DROP TABLE intranet_section_files CASCADE;
DROP TABLE intranet_sections CASCADE;
DROP TABLE mf_centres CASCADE;
DROP TABLE mf_depts CASCADE;
DROP TABLE mf_operations CASCADE;
DROP TABLE mf_resources CASCADE;
DROP TABLE mf_structures CASCADE;
DROP TABLE mf_workorders CASCADE;
DROP TABLE module_admins CASCADE;
DROP TABLE modules CASCADE;
DROP TABLE news_items CASCADE;
DROP TABLE newsletter_recipients CASCADE;
DROP TABLE newsletter_url_clicks CASCADE;
DROP TABLE newsletter_urls CASCADE;
DROP TABLE newsletter_views CASCADE;
DROP TABLE newsletters CASCADE;
DROP TABLE opportunity_notes CASCADE;
DROP TABLE order_item_additional_info CASCADE;
DROP TABLE order_item_dispatches CASCADE;
DROP TABLE order_shipments CASCADE;
DROP TABLE people_in_categories CASCADE;
DROP TABLE person_notes CASCADE;
DROP TABLE pi_header CASCADE;
DROP TABLE pi_lines CASCADE;
DROP TABLE pltransactions CASCADE;
DROP TABLE poll_options CASCADE;
DROP TABLE poll_votes CASCADE;
DROP TABLE polls CASCADE;
DROP TABLE product_attributes CASCADE;
DROP TABLE product_bundles CASCADE;
DROP TABLE product_features CASCADE;
DROP TABLE product_option_categories CASCADE;
DROP TABLE product_options CASCADE;
DROP TABLE product_related_products CASCADE;
DROP TABLE products_in_bundles CASCADE;
DROP TABLE project_categories CASCADE;
DROP TABLE project_equipment CASCADE;
DROP TABLE project_issue_statuses CASCADE;
DROP TABLE project_phases CASCADE;
DROP TABLE project_work_types CASCADE;
DROP TABLE resource_templates CASCADE;
DROP TABLE resource_types CASCADE;
DROP TABLE resources CASCADE;
DROP TABLE sales_people CASCADE;
DROP TABLE shipping_methods CASCADE;
DROP TABLE shipping_options CASCADE;
DROP TABLE si_header CASCADE;
DROP TABLE si_lines CASCADE;
DROP TABLE sltransactions CASCADE;
DROP TABLE st_balances CASCADE;
DROP TABLE st_items CASCADE;
DROP TABLE st_transactions CASCADE;
DROP TABLE store_basket_item_options CASCADE;
DROP TABLE store_basket_items CASCADE;
DROP TABLE store_baskets CASCADE;
DROP TABLE store_config CASCADE;
DROP TABLE store_dynamic_sections CASCADE;
DROP TABLE store_offer_code_uses CASCADE;
DROP TABLE store_offer_codes CASCADE;
DROP TABLE store_order_extras CASCADE;
DROP TABLE store_order_item_options CASCADE;
DROP TABLE store_order_items CASCADE;
DROP TABLE store_order_selected_extras CASCADE;
DROP TABLE store_orders CASCADE;
DROP TABLE store_product_information_requests CASCADE;
DROP TABLE store_products CASCADE;
DROP TABLE store_section_discounts CASCADE;
DROP TABLE store_sections CASCADE;
DROP TABLE store_vouchers CASCADE;
DROP TABLE sypaytypes CASCADE;
DROP TABLE syterms CASCADE;
DROP TABLE task_priorities CASCADE;
DROP TABLE tax_statuses CASCADE;
DROP TABLE taxperiods CASCADE;
DROP TABLE taxrates CASCADE;
DROP TABLE temp CASCADE;
DROP TABLE templates CASCADE;
DROP TABLE test CASCADE;
DROP TABLE testtable CASCADE;
DROP TABLE userpreferences CASCADE;
DROP TABLE webpage_categories CASCADE;
DROP TABLE webpage_revisions CASCADE;
DROP TABLE webpageroles CASCADE;
DROP TABLE webpages CASCADE;
DROP TABLE website_admins CASCADE;
DROP TABLE website_files CASCADE;
DROP TABLE website_setup CASCADE;
DROP TABLE wh_bins CASCADE;
DROP TABLE wh_locations CASCADE;
DROP TABLE wh_stores CASCADE;


-- Allow us to delete organisations with tickets
ALTER TABLE tickets DROP CONSTRAINT tickets_company_id_fkey;
ALTER TABLE tickets ADD FOREIGN KEY (organisation_id) REFERENCES organisations(id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE tickets DROP CONSTRAINT tickets_person_id_fkey;
ALTER TABLE tickets ADD FOREIGN KEY (person_id) REFERENCES people(id) ON UPDATE CASCADE ON DELETE SET NULL;
--ALTER TABLE tickets DROP CONSTRAINT tickets_queue_id_fkey;
--ALTER TABLE tickets ADD FOREIGN KEY (queue_id) REFERENCES queues(id) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE ticket_changesets DROP CONSTRAINT ticket_changesets_person_id_fkey;
ALTER TABLE ticket_changesets ADD FOREIGN KEY (person_id) REFERENCES people(id) ON UPDATE CASCADE ON DELETE SET NULL;


-- Change fkey constraints on s3_files to cascade, not set null
-- TODO!


-- Add some new indexes to speed up deletions
CREATE INDEX s3_files_organisation_id ON s3_files(organisation_id);
--CREATE INDEX s3_files_organisation ON s3_files(organisation_id, usercompanyid);
CREATE INDEX s3_files_person_id ON s3_files(person_id);
--CREATE INDEX s3_files_person ON s3_files(person_id, usercompanyid);
CREATE INDEX s3_files_opportunity_id ON s3_files(opportunity_id);
CREATE INDEX s3_files_activity_id ON s3_files(activity_id);
CREATE INDEX s3_files_usercompanyid ON s3_files(usercompanyid);
CREATE INDEX tactile_activities_usercompanyid ON tactile_activities(usercompanyid);

COMMIT;

