<?php

/**
 *
 */
class Omelette_PasswordHandler extends PasswordGenerationHandler  {

	/**
	 * Returns the md5 of the value generated by regular PasswordGeneration
	 * @see AutoHandler::handle()
	 */
	public function handle(DataObject $model) {
		return md5(parent::handle($model));
	}
}

?>
